export const UserActionTypes = {
    LOG_OUT: 'LOG_OUT',
    FETCH_LOGIN_START: 'FETCH_LOGIN_START',
    FETCH_LOGIN_START_SUCCESS: 'FETCH_LOGIN_START_SUCCESS',
    FETCH_LOGIN_START_FAILURE: 'FETCH_LOGIN_START_FAILURE',
}